Introduce OT namespce to avoid clash with other libraries
Fixes the following clash with STM32 platform from:
  https://github.com/stm32duino/Arduino_Core_STM32

opentherm_library/src/OpenTherm.h:21:2: error: 'SUCCESS' conflicts with a previous declaration
  SUCCESS,
  ^~~~~~~
In file included from /home/sw/.arduino15/packages/STM32/hardware/stm32/1.6.0-dev/cores/arduino/stm32/stm32_def.h:29,
                 from /home/sw/.arduino15/packages/STM32/hardware/stm32/1.6.0-dev/cores/arduino/stm32/clock.h:43,
                 from /home/sw/.arduino15/packages/STM32/hardware/stm32/1.6.0-dev/cores/arduino/wiring_time.h:23,
                 from /home/sw/.arduino15/packages/STM32/hardware/stm32/1.6.0-dev/cores/arduino/wiring.h:38,
                 from /home/sw/.arduino15/packages/STM32/hardware/stm32/1.6.0-dev/cores/arduino/Arduino.h:32,
                 from /home/sw/Arduino/OT-Adapter/.build/sketch/OT-Adapter.ino.cpp:1:
/home/sw/.arduino15/packages/STM32/hardware/stm32/1.6.0-dev/system/Drivers/CMSIS/Device/ST/STM32F1xx/Include/stm32f1xx.h:185:3: note: previous declaration 'ErrorStatus SUCCESS'
   SUCCESS = !ERROR
   ^~~~~~~